SELECT
	B.NAME,
	A.REQUEST_SESSION_ID,
	C.BLOCKING_SESSION_ID,
	OBJECT_NAME(P.OBJECT_ID),
	A.RESOURCE_TYPE,
	G.TEXT,
	H.TEXT,
	A.REQUEST_MODE
FROM SYS.DM_TRAN_LOCKS										AS A
JOIN SYS.DATABASES											AS B ON B.DATABASE_ID			= A.RESOURCE_DATABASE_ID
JOIN SYS.DM_OS_WAITING_TASKS								AS C ON A.LOCK_OWNER_ADDRESS	= C.RESOURCE_ADDRESS
JOIN SYS.PARTITIONS											AS D ON D.HOBT_ID				= A.RESOURCE_ASSOCIATED_ENTITY_ID
JOIN SYS.DM_EXEC_CONNECTIONS								AS E ON E.SESSION_ID			= A.REQUEST_SESSION_ID
JOIN SYS.DM_EXEC_CONNECTIONS								AS F ON F.SESSION_ID			= C.BLOCKING_SESSION_ID
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(E.MOST_RECENT_SQL_HANDLE)	AS G
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(F.MOST_RECENT_SQL_HANDLE)	AS H

--KILL BlockingSessionId