-- TABLE EXISTS
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = '@SCHEMA' AND TABLE_NAME = '@TABLE')
BEGIN
	PRINT 'TABLE EXISTS!'
END
ELSE BEGIN
	PRINT 'TABLE NOT EXISTS!'
END

-- FUNCTION EXISTS
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'FUNCTION' AND ROUTINE_SCHEMA = '@SCHEMA' AND ROUTINE_NAME = '@FUNCTION')
BEGIN
	PRINT 'FUNCTION EXISTS!'
END
ELSE BEGIN
	PRINT 'FUNCTION NOT EXISTS!'
END

-- PROCEDURE EXISTS
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE' AND ROUTINE_SCHEMA = '@SCHEMA' AND ROUTINE_NAME = '@PROCEDURE')
BEGIN
	PRINT 'PROCEDURE EXISTS!'
END
ELSE BEGIN
	PRINT 'PROCEDURE NOT EXISTS!'
END

-- COLUMN EXISTS IN A TABLE
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '@SCHEMA' AND TABLE_NAME = '@TABLE' AND COLUMN_NAME = '@COLUMN')
BEGIN
	PRINT 'COLUMN EXISTS!'
END
ELSE BEGIN
	PRINT 'COLUMN NOT EXISTS!'
END